services:
  yunzai:
    image: shuery/yunzai:latest
    build: ${DOCKER_BUILD_CONTEXT:-.}
    profiles:
      - production
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
        reservations:
          memory: 512M
    env_file: $ENV_FILE
    # environment:
    #   - YUNZAI_REPO
    #   - PLUGIN_REPOS
    #   - GITHUB_PROXY
    #   - PNPM_REGISTRY
    #   - REDIS_HOST
    #   - REDIS_PORT
    #   - REDIS_PASSWORD
    #   - REDIS_DB
    #   - QQ_ACCOUNT
    #   - QQ_PASSWORD
    working_dir: /app/yunzai
    volumes:
      - yunzai_data:/app/yunzai
    ports: [ $EXPOSE_PORTS ]
    healthcheck:
      test: [ "CMD", "pnpm", "--version" ]
      interval: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  yunzai-dev:
    build:
      context: .
      args:
        PNPM_VERSION: latest
    profiles:
      - development
    extends: yunzai

volumes:
  yunzai_data:
    name: yunzai_data
    driver: local
