services:
  yunzai:
    build:
      context: .
      args:
        PNPM_VERSION: latest
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
        reservations:
          memory: 512M
    environment:
      - YUNZAI_REPO=https://github.com/yoimiya-kokomi/Miao-Yunzai.git
      - PLUGIN_REPOS=https://github.com/yoimiya-kokomi/miao-plugin.git
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=YourWonderfulPassword!
      - REDIS_DB=0
      - QQ_ACCOUNT=1234567890
      - QQ_PASSWORD=password123
    working_dir: /app/yunzai
    volumes:
      - yunzai_data:/app/yunzai
    networks:
      - yunzai_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "pnpm", "--version" ]
      interval: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: YourWonderfulPassword!
    command: redis-server --requirepass $$REDIS_PASSWORD --save 60 1
    volumes:
      - redis_data:/data
    networks:
      - yunzai_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  yunzai_data:
    name: yunzai_data
    driver: local
  redis_data:
    name: redis_data
    driver: local

networks:
  yunzai_network:
    driver: bridge
