services:
  yunzai:
    build:
      context: .
      args:
        PNPM_VERSION: latest
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
        reservations:
          memory: 512M
    env_file: $ENV_FILE
    environment:
      - YUNZAI_REPO
      - PLUGIN_REPOS
      - GITHUB_PROXY
      - PNPM_REGISTRY
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - REDIS_DB
      - QQ_ACCOUNT
      - QQ_PASSWORD
    working_dir: /app/yunzai
    volumes:
      - yunzai_data:/app/yunzai
    networks:
      - yunzai_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "pnpm", "--version" ]
      interval: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:alpine
    env_file: $ENV_FILE
    environment:
      - REDIS_CONFIG
      - REDIS_PASSWORD
    command: redis-server $$REDIS_CONFIG --requirepass $$REDIS_PASSWORD --save 60 1
    volumes:
      - redis_data:/data
    networks:
      - yunzai_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  yunzai_data:
    name: yunzai_data
    driver: local
  redis_data:
    name: redis_data
    driver: local

networks:
  yunzai_network:
    driver: bridge
