version: "3.8"

services:
    yunzai:
      build:
        context: .
        args:
          PNPM_VERSION: latest
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          memory: 512M
    volumes:
      - yunzai_data:/opt/yunzai
    environment:
      - PNPM_HOME=/opt/yunzai/.pnpm
      - PNPM_STORE_PATH=/opt/yunzai/.pnpm/store
    working_dir: /opt/yunzai
    healthcheck:
      test: ["CMD", "pnpm", "--version"]
      interval: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  yunzai_data:
    name: yunzai_data
    driver: local
    driver_opts:
      o: bind
      type: none
